#!/usr/bin/env node
/**
 * Build client-side hydration bundles and embed them as TypeScript
 * string modules that the worker can inline.
 *
 * Why string modules instead of serving JS as a static asset?
 *
 * Same reason `build-public-css.mjs` exists: Cloudflare Workers don't
 * have a filesystem at runtime, so every byte the worker serves has to
 * either be a binding (KV / R2 / Assets / Sites), a fetched Response,
 * or code already bundled into the worker module itself. For a tiny
 * hydration script (a few KB) it is simplest to compile it into a TS
 * string constant and inline it via `<script>...</script>` in the
 * rendered HTML.
 *
 * The alternative — a `[[assets]]` binding pointing at a `public/`
 * directory — is tracked in `docs/plans/...md §7.2` as a longer-term
 * option but adds wrangler.toml dual-binding complexity. Faz 3 defers
 * that work; we can swap the transport later without touching the
 * client source.
 *
 * Pipeline per entry:
 *   1. esbuild bundle → IIFE, ES2022, minified, external: none
 *   2. Read resulting bytes as a UTF-8 string
 *   3. Escape backticks + backslashes + `${` for TS template literal
 *   4. Write `src/ssr/__generated__/<name>-client.ts` with an exported
 *      `<NAME>_CLIENT_JS` constant.
 *
 * Adding a new entry: append to the ENTRIES array below.
 */

import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import * as esbuild from 'esbuild';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, '..');

/**
 * @type {Array<{ name: string, entry: string, out: string, exportName: string }>}
 */
const ENTRIES = [
  {
    name: 'landing',
    entry: resolve(ROOT, 'src/client/landing-entry.tsx'),
    out: resolve(ROOT, 'src/ssr/__generated__/landing-client.ts'),
    exportName: 'LANDING_CLIENT_JS',
  },
];

/**
 * Escape a JS source string so it can be safely embedded inside a
 * TypeScript backtick template literal. Three things break templates:
 *   \  — escape first so our own escapes don't get re-escaped
 *   `  — ends the literal
 *   ${ — starts a template expression
 */
function escapeForTemplateLiteral(source) {
  return source
    .replace(/\\/g, '\\\\')
    .replace(/`/g, '\\`')
    .replace(/\$\{/g, '\\${');
}

async function buildEntry({ name, entry, out, exportName }) {
  const start = Date.now();
  console.log(`[build-client] bundling ${name}…`);

  const result = await esbuild.build({
    entryPoints: [entry],
    bundle: true,
    write: false,
    format: 'iife',
    target: 'es2022',
    platform: 'browser',
    minify: true,
    jsx: 'automatic',
    jsxImportSource: 'react',
    loader: { '.tsx': 'tsx', '.ts': 'ts' },
    // react-dom/client pulls in development runtimes unless NODE_ENV is
    // set — this cuts the bundle by ~60 %.
    define: { 'process.env.NODE_ENV': '"production"' },
    logLevel: 'warning',
    // Resolve the `@ui/*` alias the same way tsconfig does. Without
    // this esbuild treats `@ui/button` as a package lookup.
    alias: {
      '@ui': resolve(ROOT, 'packages/ui'),
    },
  });

  if (result.outputFiles.length !== 1) {
    throw new Error(
      `[build-client] ${name}: expected 1 output file, got ${result.outputFiles.length}`
    );
  }

  const js = result.outputFiles[0].text;
  const sizeKB = (Buffer.byteLength(js, 'utf8') / 1024).toFixed(1);
  const escaped = escapeForTemplateLiteral(js);

  const ts = `// Auto-generated by scripts/build-client.mjs.
// Do NOT edit by hand — changes will be overwritten on next build.
// Source: src/client/${name}-entry.tsx
//
// This file is imported by route handlers to inline the hydration
// bundle via <script>${exportName}</script>. See build-client.mjs for
// the rationale behind shipping client JS as a TS string constant
// instead of a static asset at /assets/client/${name}.js.

export const ${exportName} = \`${escaped}\`;
`;

  mkdirSync(dirname(out), { recursive: true });
  writeFileSync(out, ts, 'utf8');
  console.log(`[build-client] done (${sizeKB} KB, ${Date.now() - start} ms) → ${out}`);
}

async function main() {
  for (const entry of ENTRIES) {
    await buildEntry(entry);
  }
}

main().catch((err) => {
  console.error('[build-client] failed:', err);
  process.exit(1);
});
