// Generates src/ssr/__generated__/version.ts with the app version derived
// from the total git commit count, in the form `v0.<commits>`.
//
// Run as part of `build:assets` (before dev/deploy) so the deployed footer
// always reflects the exact commit count of the build. The output file is
// gitignored (lives under src/ssr/__generated__/), exactly like the
// Tailwind and client-island artifacts — so it never feeds back into the
// commit count it reports.
import { execSync } from 'node:child_process';
import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const OUT = resolve(ROOT, 'src/ssr/__generated__/version.ts');

let count = 0;
try {
  count = parseInt(execSync('git rev-list --count HEAD', { cwd: ROOT }).toString().trim(), 10) || 0;
} catch {
  // No git history available (e.g. shallow CI checkout) — fall back to 0.
  count = 0;
}

const version = `v0.${count}`;
mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(
  OUT,
  `// AUTO-GENERATED by scripts/gen-version.mjs — do not edit.\n` +
    `// Version tracks the total git commit count as v0.<commits>.\n` +
    `export const APP_VERSION = '${version}';\n`
);
console.log('[gen-version]', OUT, '→', version);
