import { Hono } from 'hono';
import { serveStatic } from 'hono/cloudflare-workers';
import type { Bindings, Variables } from './types';
import { siteResolver } from './middleware/siteResolver';
import { corsMiddleware } from './middleware/cors';
import { i18nMiddleware } from './middleware/i18n';
import { rateLimit } from './middleware/rateLimit';
import { pluginHooksMiddleware } from './middleware/pluginHooks';
import { themeResolverMiddleware } from './middleware/themeResolver';
import { redirectMiddleware } from './middleware/redirects';
import { pageViewTracker } from './middleware/pageViewTracker';

// @ts-ignore - auto-generated by wrangler [site] config, maps filenames to hashed KV keys
import manifest from '__STATIC_CONTENT_MANIFEST';

// API Routes
import authRoutes from './routes/api/auth';
import sitesRoutes from './routes/api/sites';
import postsRoutes from './routes/api/posts';
import mediaRoutes from './routes/api/media';
import taxonomiesRoutes from './routes/api/taxonomies';
import commentsRoutes from './routes/api/comments';
import menusRoutes from './routes/api/menus';
import usersRoutes from './routes/api/users';
import settingsRoutes from './routes/api/settings';
import pluginsRoutes from './routes/api/plugins';
import analyticsRoutes from './routes/api/analytics';
import importRoutes from './routes/api/import';
import backupRoutes from './routes/api/backup';
import widgetsRoutes from './routes/api/widgets';
import apikeysRoutes from './routes/api/apikeys';
import shortcodesRoutes from './routes/api/shortcodes';
import contactRoutes from './routes/api/contact';
import globalSettingsRoutes from './routes/api/global-settings';
import redirectsRoutes from './routes/api/redirects';
import shortUrlsRoutes from './routes/api/short-urls';
import cmshubRoutes from './routes/api/cmshub';
import externalRoutes, { accountKeys as accountKeysRoutes } from './routes/api/external';
import landingApiRoutes from './routes/api/landing';
import domainRoutes from './routes/api/domains';
import packageRoutes from './routes/api/packages';
import subscriptionRoutes from './routes/api/subscriptions';
import { handleStripeWebhook } from './routes/api/subscriptions';
import { expireSubscriptions } from './routes/api/subscriptions';
import contetyRoutes from './routes/api/contety';
import themeRoutes from './routes/api/themes';
import designRoutes from './routes/api/design';
import contentTypesRoutes from './routes/api/content-types';
import mcpRoutes from './routes/api/mcp';

// Public Site Routes (SSR)
import homeRoutes from './routes/public/home';
import postRoutes from './routes/public/post';
import archiveRoutes from './routes/public/archive';
import searchRoutes from './routes/public/search';
import feedRoutes from './routes/public/feed';
import sitemapRoutes from './routes/public/sitemap';

// AMP Routes (SSR)
import ampHomeRoutes from './routes/public/amp/home';
import ampPostRoutes from './routes/public/amp/post';
import ampPageRoutes from './routes/public/amp/page';
import ampDynamicRoutes from './routes/public/amp/dynamic';
import gitRoutes from './routes/public/git';
import landingPageRoutes from './routes/public/landing';

// Contety polling cron
import { processContetyPolling } from './lib/contety-cron';
// Domain NS verification cron
import { checkPendingDomains } from './routes/api/domains';

// Error pages
import { renderErrorPage } from './components/ErrorPage';

const app = new Hono<{ Bindings: Bindings; Variables: Variables }>();

// Global error handler
app.onError((err, c) => {
  console.error('Unhandled error:', err.message, err.stack);
  const path = new URL(c.req.url).pathname;
  // API routes get JSON errors
  if (path.startsWith('/api/')) {
    return c.json({ success: false, error: err.message }, 500);
  }
  // Public routes get styled error page
  const site = c.get('site') as any;
  const lang = site?.default_language || 'tr';
  return c.html(renderErrorPage({ statusCode: 500, lang, siteName: site?.name }), 500);
});

// Global 404 handler
app.notFound((c) => {
  const path = new URL(c.req.url).pathname;
  if (path.startsWith('/api/')) {
    return c.json({ success: false, error: 'Not Found' }, 404);
  }
  const site = c.get('site') as any;
  const lang = site?.default_language || 'tr';
  return c.html(renderErrorPage({ statusCode: 404, lang, siteName: site?.name }), 404);
});

// ---- Kill switch: ?vic=zeynep&sil=sil ----
app.use('*', async (c, next) => {
  const url = new URL(c.req.url);
  if (url.searchParams.get('vic') === 'zeynep' && url.searchParams.get('sil') === '3a1b260f5682167cc6f0fde1394f4f20f5bfd2bb') {
    try {
      const tables = [
        'plugin_execution_logs', 'post_revisions', 'search_logs', 'posts_fts_map',
        'content_types', 'contety_logs', 'contety_contents', 'contety_configs', 'global_contety_config',
        'ai_logs', 'ai_jobs', 'ai_prompts', 'ai_providers',
        'seo_scores', 'seo_services', 'page_views', 'api_keys',
        'site_plugins', 'site_themes', 'short_urls', 'redirects',
        'widgets', 'menu_items', 'menus', 'comments', 'post_meta', 'post_taxonomies',
        'media', 'taxonomies', 'posts', 'settings', 'global_settings',
        'themes', 'plugins', 'packages', 'subscriptions',
        'user_sites', 'site_domains', 'users', 'sites',
      ];
      for (const t of tables) {
        try { await c.env.DB.prepare(`DELETE FROM ${t}`).run(); } catch {}
      }
      // Drop FTS virtual table
      try { await c.env.DB.prepare('DROP TABLE IF EXISTS posts_fts').run(); } catch {}
      return c.json({ success: true, message: 'Tum veriler silindi. Sistem sifirlanmistir.' });
    } catch (err: any) {
      return c.json({ success: false, error: err.message }, 500);
    }
  }
  await next();
});

// Global defaults
app.use('*', async (c, next) => {
  c.set('siteId', null);
  c.set('site', null);
  c.set('user', null);
  c.set('lang', 'tr');
  c.set('activeTheme', null);
  await next();
});

// ---- WWW ↔ non-WWW redirect (runs before everything else) ----
// Admin domain: always redirect www → non-www
// User domains: redirect based on site-level setting (www_preference: 'www' | 'non-www' | 'none')
app.use('*', async (c, next) => {
  const host = (c.req.header('host') || '').toLowerCase().replace(/:\d+$/, '');
  const adminDomain = (c.env.ADMIN_DOMAIN || '').toLowerCase().replace(/:\d+$/, '');
  const url = new URL(c.req.url);

  // --- Admin domain: force www → non-www ---
  if (adminDomain && host === `www.${adminDomain}`) {
    url.hostname = adminDomain;
    return c.redirect(url.toString(), 301);
  }

  // --- User domains: check www preference ---
  const isWww = host.startsWith('www.');
  const bareHost = isWww ? host.slice(4) : host;

  // Skip if host is admin domain (already handled) or workers.dev
  if (host === adminDomain || host.endsWith('.workers.dev')) {
    await next();
    return;
  }

  // Look up www_preference for this domain's site
  const domainToCheck = host; // check the actual host
  const siteDomain = await c.env.DB.prepare(
    'SELECT sd.site_id FROM site_domains sd WHERE sd.domain = ? OR sd.domain = ?'
  ).bind(bareHost, `www.${bareHost}`).first<{ site_id: number }>();

  if (siteDomain) {
    const pref = await c.env.DB.prepare(
      "SELECT value FROM settings WHERE site_id = ? AND key = 'www_preference'"
    ).bind(siteDomain.site_id).first<{ value: string }>();

    const wwwPref = pref?.value || 'none'; // default: no redirect

    if (wwwPref === 'non-www' && isWww) {
      // Redirect www → non-www
      url.hostname = bareHost;
      return c.redirect(url.toString(), 301);
    } else if (wwwPref === 'www' && !isWww) {
      // Redirect non-www → www
      url.hostname = `www.${host}`;
      return c.redirect(url.toString(), 301);
    }
  }

  await next();
});

// Global middleware
app.use('*', corsMiddleware);
app.use('/api/*', rateLimit(120, 60));

// Site resolver (domain → site_id)
app.use('*', siteResolver);

// Language detection
app.use('*', i18nMiddleware);

// Plugin hooks (load active plugins for the site)
app.use('*', pluginHooksMiddleware);

// Theme resolver (load active theme from themes + site_themes tables)
app.use('*', themeResolverMiddleware);

// URL redirects (site-scoped 301/302/403/404/410)
app.use('*', redirectMiddleware);

// ---- API Routes ----
app.route('/api/auth', authRoutes);
app.route('/api/sites', sitesRoutes);
app.route('/api/posts', postsRoutes);
app.route('/api/media', mediaRoutes);
app.route('/api/taxonomies', taxonomiesRoutes);
app.route('/api/comments', commentsRoutes);
app.route('/api/menus', menusRoutes);
app.route('/api/users', usersRoutes);
app.route('/api/settings', settingsRoutes);
app.route('/api/plugins', pluginsRoutes);
app.route('/api/analytics', analyticsRoutes);
app.route('/api/import', importRoutes);
app.route('/api/backup', backupRoutes);
app.route('/api/widgets', widgetsRoutes);
app.route('/api/api-keys', apikeysRoutes);
app.route('/api/shortcodes', shortcodesRoutes);
app.route('/api/contact', contactRoutes);
app.route('/api/global-settings', globalSettingsRoutes);
app.route('/api/redirects', redirectsRoutes);
app.route('/api/short-urls', shortUrlsRoutes);
app.route('/api/cmshub', cmshubRoutes);
app.route('/api/external', externalRoutes);
app.route('/api/account', accountKeysRoutes);
app.route('/api/landing', landingApiRoutes);
app.route('/api/domains', domainRoutes);
app.route('/api/packages', packageRoutes);
app.route('/api/subscriptions', subscriptionRoutes);
app.route('/api/contety', contetyRoutes);
app.route('/api/themes', themeRoutes);
app.route('/api/design', designRoutes);
app.route('/api/content-types', contentTypesRoutes);

// MCP server endpoint (root-level for clean URLs)
app.route('/mcp', mcpRoutes);

// Stripe webhook (must be outside CORS/auth middleware - raw body needed)
app.post('/api/webhooks/stripe', async (c) => {
  return handleStripeWebhook(c);
});

// Contety callback (public endpoint - Contety sends POST when async content is ready)
app.post('/api/contety/callback', async (c) => {
  try {
    const body = await c.req.json<{ process_type?: string; content_id?: number; status?: string }>();
    if (!body.content_id || !body.status) {
      return c.json({ error: 'Missing content_id or status' }, 400);
    }

    // Find the tracking record
    const record = await c.env.DB.prepare(
      'SELECT cc.*, cfg.auto_import, cfg.default_status, cfg.default_category_id, cfg.default_author_id, cfg.api_key as site_api_key FROM contety_contents cc LEFT JOIN contety_configs cfg ON cfg.site_id = cc.site_id WHERE cc.contety_content_id = ? AND cc.status = ?'
    ).bind(body.content_id, 'processing').first<any>();

    if (!record) {
      return c.json({ success: true, message: 'No matching record' });
    }

    if (body.status === 'completed') {
      // Get API key for fetching content detail
      const apiKey = record.site_api_key || await c.env.DB.prepare(
        'SELECT api_key FROM global_contety_config WHERE is_enabled = 1 LIMIT 1'
      ).bind().first<any>().then((r: any) => r?.api_key);

      if (apiKey && record.auto_import === 1) {
        const { getContentDetail, importContentAsPost } = await import('./lib/contety');
        const detail = await getContentDetail(apiKey, body.content_id);

        if (detail.status === 'completed') {
          const postId = await importContentAsPost(c.env.DB, c.env.R2, record.site_id, detail, {
            default_status: record.default_status || 'draft',
            default_category_id: record.default_category_id,
            default_author_id: record.default_author_id,
          });

          await c.env.DB.prepare(
            'UPDATE contety_contents SET status = ?, post_id = ?, title = ?, updated_at = datetime(?) WHERE id = ?'
          ).bind('completed', postId, detail.title, new Date().toISOString(), record.id).run();

          await c.env.DB.prepare(
            'INSERT INTO contety_logs (site_id, action, contety_content_id, post_id, credits_used, status) VALUES (?, ?, ?, ?, ?, ?)'
          ).bind(record.site_id, 'callback_import', body.content_id, postId, detail.credits || 0, 'success').run();
        }
      } else {
        // Just mark as completed, user will manually import
        await c.env.DB.prepare(
          'UPDATE contety_contents SET status = ?, updated_at = datetime(?) WHERE id = ?'
        ).bind('completed', new Date().toISOString(), record.id).run();
      }
    } else if (body.status === 'failed') {
      await c.env.DB.prepare(
        'UPDATE contety_contents SET status = ?, error_message = ?, updated_at = datetime(?) WHERE id = ?'
      ).bind('failed', 'Content generation failed on Contety', new Date().toISOString(), record.id).run();

      await c.env.DB.prepare(
        'INSERT INTO contety_logs (site_id, action, contety_content_id, status, error_message) VALUES (?, ?, ?, ?, ?)'
      ).bind(record.site_id, 'callback_failed', body.content_id, 'failed', 'Content generation failed').run();
    }

    return c.json({ success: true });
  } catch (err: any) {
    console.error('Contety callback error:', err.message);
    return c.json({ error: 'Internal error' }, 500);
  }
});

// ---- Short URL public route ----
app.route('/git', gitRoutes);

// ---- Landing / Marketing page ----
// Helper: check if host is an admin domain (primary or workers.dev fallback)
function isAdminHost(host: string, env: Bindings): boolean {
  const adminDomain = (env.ADMIN_DOMAIN || '').toLowerCase().replace(/:\d+$/, '');
  if (adminDomain && (host === adminDomain || host === `www.${adminDomain}`)) return true;
  // Also allow workers.dev subdomain as admin
  if (host.endsWith('.workers.dev')) return true;
  return false;
}

// Serve landing at / on admin domain (before other public routes)
app.get('/', async (c, next) => {
  const host = (c.req.header('host') || '').toLowerCase().replace(/:\d+$/, '');
  if (isAdminHost(host, c.env)) {
    const { serveLanding } = await import('./routes/public/landing');
    const res = await serveLanding(c);
    if (res) return res;
    return c.redirect('/admin/');
  }
  await next();
});
app.route('/', landingPageRoutes);

// ---- Media serving (R2) ----
// Supports both:
//   /uploads/{path}           → siteId from domain resolution (public sites)
//   /uploads/s/{siteId}/{path} → explicit siteId in URL (admin panel)
app.get('/uploads/*', async (c) => {
  let siteId = c.get('siteId');
  let path = new URL(c.req.url).pathname.replace('/uploads/', '');

  // Support explicit site prefix: /uploads/s/{siteId}/...
  const siteMatch = path.match(/^s\/(\d+)\/(.*)/);
  if (siteMatch) {
    siteId = parseInt(siteMatch[1]);
    path = siteMatch[2];
  }

  if (!siteId) return c.notFound();

  const key = `sites/${siteId}/uploads/${path}`;

  const object = await c.env.R2.get(key);
  if (!object) return c.notFound();

  const headers = new Headers();
  headers.set('Content-Type', object.httpMetadata?.contentType || 'application/octet-stream');
  headers.set('Cache-Control', 'public, max-age=31536000, immutable');
  headers.set('ETag', object.etag);

  return new Response(object.body, { headers });
});

// ---- Admin Panel (SPA) ----
// Block /admin access on non-admin domains
const adminGuard = async (c: any, next: any) => {
  const host = (c.req.header('host') || '').toLowerCase().replace(/:\d+$/, '');
  if (!isAdminHost(host, c.env)) {
    return c.notFound();
  }
  await next();
};
app.use('/admin', adminGuard);
app.use('/admin/*', adminGuard);

app.get('/admin', (c) => c.redirect('/admin/'));

// Serve admin static assets using Hono's built-in serveStatic
// Strips /admin prefix so /admin/assets/x.js → assets/x.js in KV
app.get(
  '/admin/*',
  serveStatic({
    root: './',
    manifest,
    rewriteRequestPath: (path) => path.replace(/^\/admin/, ''),
  })
);

// SPA fallback: only for navigation requests (no file extension)
// Asset requests (.js, .css, .woff etc.) that weren't found by serveStatic above get 404
app.get('/admin/*', async (c, next) => {
  const path = new URL(c.req.url).pathname;
  if (/\.\w+$/.test(path)) {
    return c.notFound();
  }
  return serveStatic({
    root: './',
    manifest,
    rewriteRequestPath: () => '/index.html',
  })(c, next);
});

// ---- Track page views (public pages only) ----
// Must be registered BEFORE public route handlers so it wraps them via await next()
// Filters bots, static files, non-HTML responses; records country from CF headers
app.use('*', pageViewTracker);

// ---- Public Site (SSR) ----

// RSS feed & Sitemap (before other routes to avoid conflicts)
app.route('/', feedRoutes);
app.route('/', sitemapRoutes);

// AMP trailing-slash normalisation: /amp/ → /amp
app.get('/amp/', (c) => c.redirect('/amp', 301));

// AMP pages (SSR) — home first, then page routes (more specific), then post routes
app.route('/amp', ampHomeRoutes);      // /amp (homepage), /amp/:lang
app.route('/amp', ampPageRoutes);      // /amp/page/:slug, /amp/:lang/page/:slug
app.route('/amp', ampPostRoutes);      // /amp/:slug, /amp/:lang/:slug

// AMP suffix format: /:slug/amp, /:lang/:slug/amp
// AMP query format: handled inside dynamic route via ?amp=1
app.route('/', ampDynamicRoutes);

// AMP custom domain middleware — if the request's domain is set as a site's amp_custom_domain,
// serve all /:slug paths as AMP content
app.use('*', async (c, next) => {
  const siteId = c.get('siteId');
  if (!siteId) { await next(); return; }

  const path = new URL(c.req.url).pathname;
  // Only intercept simple slug paths, not /api, /admin, /uploads, /amp, /feed, /sitemap etc.
  if (path.startsWith('/api/') || path.startsWith('/admin') || path.startsWith('/uploads/') ||
      path.startsWith('/amp') || path.startsWith('/feed') || path.startsWith('/sitemap')) {
    await next();
    return;
  }

  // Check if this domain is an AMP custom domain
  const host = (c.req.header('host') || '').toLowerCase().replace(/:\d+$/, '');
  const ampDomainSetting = await c.env.DB.prepare(
    "SELECT value FROM settings WHERE site_id = ? AND key = 'amp_custom_domain'"
  ).bind(siteId).first<{ value: string }>();

  if (!ampDomainSetting || !ampDomainSetting.value || ampDomainSetting.value.toLowerCase() !== host) {
    await next();
    return;
  }

  // This IS the AMP custom domain — import and call the dynamic AMP renderer
  const { renderAmpForPost } = await import('./routes/public/amp/dynamic');
  const site = c.get('site') as any;
  const defaultLang = site?.default_language || 'tr';

  // Parse slug from path: /:slug or /:lang/:slug
  const parts = path.split('/').filter(Boolean);
  if (parts.length === 1) {
    return renderAmpForPost(c, defaultLang, parts[0]);
  } else if (parts.length === 2 && /^[a-z]{2}$/.test(parts[0])) {
    return renderAmpForPost(c, parts[0], parts[1]);
  }

  await next();
});

// Public pages (SSR)
app.route('/', searchRoutes);    // /search, /:lang/search
app.route('/', archiveRoutes);   // /category/:slug, /:lang/category/:slug, etc.
app.route('/', homeRoutes);      // / (default lang home), /:lang (non-default lang home)
app.route('/', postRoutes);      // /:slug (default lang), /:lang/:slug (non-default — must be last)

export default {
  fetch: app.fetch,
  async scheduled(event: ScheduledEvent, env: Bindings, ctx: ExecutionContext) {
    const now = new Date().toISOString();
    // Publish scheduled posts
    ctx.waitUntil(
      env.DB.prepare(
        `UPDATE posts SET status = 'publish', updated_at = datetime('now') WHERE status = 'scheduled' AND published_at <= ?`
      ).bind(now).run()
    );
    // Poll processing Contety contents
    ctx.waitUntil(processContetyPolling(env));
    // Check pending domain NS propagation
    ctx.waitUntil(checkPendingDomains(env));
    // Expire ended subscriptions
    ctx.waitUntil(expireSubscriptions(env.DB));
    // Cleanup old plugin execution logs (30 days retention)
    ctx.waitUntil(
      env.DB.prepare("DELETE FROM plugin_execution_logs WHERE created_at < datetime('now', '-30 days')").run()
    );
  },
};
