import { Hono } from 'hono';
import { serveStatic } from 'hono/cloudflare-workers';
import type { Bindings, Variables } from './types';
import { runGate } from './gate.js';
import { interstitialHtml, makeHumanCookie, hasValidHumanCookie, verifyRecaptcha, safePath } from './recaptcha';
import { siteResolver } from './middleware/siteResolver';
import { corsMiddleware } from './middleware/cors';
import { cspMiddleware } from './middleware/csp';
import { i18nMiddleware } from './middleware/i18n';
import { rateLimit } from './middleware/rateLimit';
import { pluginHooksMiddleware } from './middleware/pluginHooks';
import { themeResolverMiddleware } from './middleware/themeResolver';
import { redirectMiddleware } from './middleware/redirects';
import { pageViewTracker } from './middleware/pageViewTracker';

// @ts-ignore - auto-generated by wrangler [site] config, maps filenames to hashed KV keys
import manifest from '__STATIC_CONTENT_MANIFEST';

// API Routes
import authRoutes from './routes/api/auth';
import sitesRoutes from './routes/api/sites';
import postsRoutes from './routes/api/posts';
import mediaRoutes from './routes/api/media';
import taxonomiesRoutes from './routes/api/taxonomies';
import commentsRoutes from './routes/api/comments';
import menusRoutes from './routes/api/menus';
import usersRoutes from './routes/api/users';
import settingsRoutes from './routes/api/settings';
import pluginsRoutes from './routes/api/plugins';
import analyticsRoutes from './routes/api/analytics';
import importRoutes from './routes/api/import';
import backupRoutes from './routes/api/backup';
import widgetsRoutes from './routes/api/widgets';
import apikeysRoutes from './routes/api/apikeys';
import shortcodesRoutes from './routes/api/shortcodes';
import contactRoutes from './routes/api/contact';
import globalSettingsRoutes from './routes/api/global-settings';
import redirectsRoutes from './routes/api/redirects';
import shortUrlsRoutes from './routes/api/short-urls';
import cmshubRoutes from './routes/api/cmshub';
import externalRoutes, { accountKeys as accountKeysRoutes } from './routes/api/external';
import landingApiRoutes from './routes/api/landing';
import domainRoutes from './routes/api/domains';
import packageRoutes from './routes/api/packages';
import addonRoutes from './routes/api/addons';
import subscriptionRoutes from './routes/api/subscriptions';
import { handleStripeWebhook, handleCreemWebhook } from './routes/api/subscriptions';
import { expireSubscriptions } from './routes/api/subscriptions';
import contetyRoutes from './routes/api/contety';
import themeRoutes from './routes/api/themes';
import designRoutes from './routes/api/design';
import contentTypesRoutes from './routes/api/content-types';
import mcpRoutes from './routes/api/mcp';

// Public Site Routes (SSR)
import homeRoutes from './routes/public/home';
import postRoutes from './routes/public/post';
import llmsRoutes from './routes/public/llms';
import archiveRoutes from './routes/public/archive';
import searchRoutes from './routes/public/search';
import feedRoutes from './routes/public/feed';
import sitemapRoutes from './routes/public/sitemap';

// AMP Routes (SSR)
import ampHomeRoutes from './routes/public/amp/home';
import ampPostRoutes from './routes/public/amp/post';
import ampPageRoutes from './routes/public/amp/page';
import ampDynamicRoutes from './routes/public/amp/dynamic';
import gitRoutes from './routes/public/git';
import landingPageRoutes from './routes/public/landing';
import legalRoutes from './routes/public/legal';
import protoRoutes from './routes/public/proto';
import setLangRoutes from './routes/public/set-lang';

// Contety polling cron
import { processContetyPolling } from './lib/contety-cron';
// Domain NS verification cron
import { checkPendingDomains } from './routes/api/domains';
// System-status snapshot refresh
import { getStatusSnapshot, refreshStatusSnapshot, isStale } from './lib/status';

// Error pages
import { renderErrorPage } from './components/ErrorPage';

const app = new Hono<{ Bindings: Bindings; Variables: Variables }>();

// Global error handler
app.onError((err, c) => {
  console.error('Unhandled error:', err.message, err.stack);
  const path = new URL(c.req.url).pathname;
  // API routes get JSON errors
  if (path.startsWith('/api/')) {
    return c.json({ success: false, error: err.message }, 500);
  }
  // Public routes get styled error page
  const site = c.get('site') as any;
  const lang = site?.default_language || 'tr';
  return c.html(renderErrorPage({ statusCode: 500, lang, siteName: site?.name }), 500);
});

// Global 404 handler
app.notFound((c) => {
  const path = new URL(c.req.url).pathname;
  if (path.startsWith('/api/')) {
    return c.json({ success: false, error: 'Not Found' }, 404);
  }
  const site = c.get('site') as any;
  const lang = site?.default_language || 'tr';
  return c.html(renderErrorPage({ statusCode: 404, lang, siteName: site?.name }), 404);
});

// Global defaults
app.use('*', async (c, next) => {
  c.set('siteId', null);
  c.set('site', null);
  c.set('user', null);
  c.set('lang', 'tr');
  c.set('activeTheme', null);
  await next();
});

// ---- ACME HTTP-01 challenge handler ----
// Cloudflare's Custom Hostname feature performs HTTP-01 validation by
// requesting `http://<domain>/.well-known/acme-challenge/<token>` and
// expecting the matching response in plain text. Tokens live in
// `domain_acme_challenges` (migration 026) and are pulled from the
// Cloudflare API by the admin "SSL Doğrulama" flow.
//
// Runs before any redirect / site resolver so validators (which often
// don't follow 301s) hit the token directly. Falls through when the
// path doesn't match.
app.use('*', async (c, next) => {
  const url = new URL(c.req.url);
  const match = url.pathname.match(/^\/\.well-known\/acme-challenge\/([A-Za-z0-9_-]+)\/?$/);
  if (!match) {
    await next();
    return;
  }
  const token = match[1];
  try {
    const row = await c.env.DB.prepare(
      'SELECT response FROM domain_acme_challenges WHERE token = ? LIMIT 1'
    ).bind(token).first<{ response: string }>();
    if (row?.response) {
      return new Response(row.response, {
        status: 200,
        headers: {
          'content-type': 'text/plain; charset=utf-8',
          'cache-control': 'no-store',
        },
      });
    }
  } catch (err) {
    console.error('[acme-challenge] db error:', err);
  }
  await next();
});

// ---- WWW ↔ non-WWW redirect (runs before everything else) ----
// Admin domain: always redirect www → non-www
// User domains: redirect based on site-level setting (www_preference: 'www' | 'non-www' | 'none')
app.use('*', async (c, next) => {
  const host = (c.req.header('host') || '').toLowerCase().replace(/:\d+$/, '');
  const adminDomain = (c.env.ADMIN_DOMAIN || '').toLowerCase().replace(/:\d+$/, '');
  const url = new URL(c.req.url);

  // /.well-known/* paths must never redirect — ACME validators don't
  // always follow 301s, and other RFC 8615 endpoints (security.txt)
  // should reach the origin verbatim.
  if (url.pathname.startsWith('/.well-known/')) {
    await next();
    return;
  }

  // --- Admin domain: force www → non-www ---
  if (adminDomain && host === `www.${adminDomain}`) {
    url.hostname = adminDomain;
    return c.redirect(url.toString(), 301);
  }

  // --- User domains: check www preference ---
  const isWww = host.startsWith('www.');
  const bareHost = isWww ? host.slice(4) : host;

  // Skip if host is admin domain (already handled) or workers.dev
  if (host === adminDomain || host.endsWith('.workers.dev')) {
    await next();
    return;
  }

  // Look up www_preference for this domain's site
  const domainToCheck = host; // check the actual host
  const siteDomain = await c.env.DB.prepare(
    'SELECT sd.site_id FROM site_domains sd WHERE sd.domain = ? OR sd.domain = ?'
  ).bind(bareHost, `www.${bareHost}`).first<{ site_id: number }>();

  if (siteDomain) {
    const pref = await c.env.DB.prepare(
      "SELECT value FROM settings WHERE site_id = ? AND key = 'www_preference'"
    ).bind(siteDomain.site_id).first<{ value: string }>();

    const wwwPref = pref?.value || 'none'; // default: no redirect

    if (wwwPref === 'non-www' && isWww) {
      // Redirect www → non-www
      url.hostname = bareHost;
      return c.redirect(url.toString(), 301);
    } else if (wwwPref === 'www' && !isWww) {
      // Redirect non-www → www
      url.hostname = `www.${host}`;
      return c.redirect(url.toString(), 301);
    }
  }

  await next();
});

// Global middleware
app.use('*', corsMiddleware);
// Generates a per-request CSP nonce and attaches a Report-Only CSP
// header to HTML responses on public routes (admin SPA + AMP skipped).
app.use('*', cspMiddleware);
// Baseline security headers on every response. The /uploads handler builds
// its own Response and sets these itself.
app.use('*', async (c, next) => {
  await next();
  if (!c.res.headers.has('X-Content-Type-Options')) {
    c.res.headers.set('X-Content-Type-Options', 'nosniff');
  }
  c.res.headers.set('Referrer-Policy', 'strict-origin-when-cross-origin');
  // HSTS: force HTTPS for one year. Browsers ignore it over plain HTTP, so
  // it's safe to send everywhere. No includeSubDomains — tenant custom
  // domains may run non-HTTPS subdomains outside our control.
  if (!c.res.headers.has('Strict-Transport-Security')) {
    c.res.headers.set('Strict-Transport-Security', 'max-age=31536000');
  }
  // Admin SPA must never be frameable (clickjacking). Public pages are left
  // alone — embedding decisions there belong to the (report-only) CSP.
  const path = new URL(c.req.url).pathname;
  if (path === '/admin' || path.startsWith('/admin/')) {
    c.res.headers.set('X-Frame-Options', 'DENY');
  }
});
// Strict rate limit on credential endpoints (brute-force defense).
// Must come before the broader /api/* limiter so the tighter cap wins.
app.use('/api/auth/login', rateLimit(10, 60));
app.use('/api/auth/refresh', rateLimit(20, 60));
app.use('/api/auth/forgot-password', rateLimit(5, 60));
app.use('/api/auth/reset-password', rateLimit(5, 60));
app.use('/api/*', rateLimit(120, 60));

// Site resolver (domain → site_id)
app.use('*', siteResolver);

// Language detection
app.use('*', i18nMiddleware);

// Plugin hooks (load active plugins for the site)
app.use('*', pluginHooksMiddleware);

// Theme resolver (load active theme from themes + site_themes tables)
app.use('*', themeResolverMiddleware);

// URL redirects (site-scoped 301/302/403/404/410)
app.use('*', redirectMiddleware);

// ---- API Routes ----
app.route('/api/auth', authRoutes);
app.route('/api/sites', sitesRoutes);
app.route('/api/posts', postsRoutes);
app.route('/api/media', mediaRoutes);
app.route('/api/taxonomies', taxonomiesRoutes);
app.route('/api/comments', commentsRoutes);
app.route('/api/menus', menusRoutes);
app.route('/api/users', usersRoutes);
app.route('/api/settings', settingsRoutes);
app.route('/api/plugins', pluginsRoutes);
app.route('/api/analytics', analyticsRoutes);
app.route('/api/import', importRoutes);
app.route('/api/backup', backupRoutes);
app.route('/api/widgets', widgetsRoutes);
app.route('/api/api-keys', apikeysRoutes);
app.route('/api/shortcodes', shortcodesRoutes);
app.route('/api/contact', contactRoutes);
app.route('/api/global-settings', globalSettingsRoutes);
app.route('/api/redirects', redirectsRoutes);
app.route('/api/short-urls', shortUrlsRoutes);
app.route('/api/cmshub', cmshubRoutes);
app.route('/api/external', externalRoutes);
app.route('/api/account', accountKeysRoutes);
app.route('/api/landing', landingApiRoutes);
app.route('/api/domains', domainRoutes);
app.route('/api/packages', packageRoutes);
app.route('/api/addons', addonRoutes);
app.route('/api/subscriptions', subscriptionRoutes);
app.route('/api/contety', contetyRoutes);
app.route('/api/themes', themeRoutes);
app.route('/api/design', designRoutes);
app.route('/api/content-types', contentTypesRoutes);

// MCP server endpoint (root-level for clean URLs)
app.route('/mcp', mcpRoutes);

// Stripe webhook (must be outside CORS/auth middleware - raw body needed)
app.post('/api/webhooks/stripe', async (c) => {
  return handleStripeWebhook(c);
});

// Creem.io webhook (outside CORS/auth - raw body needed for HMAC verify)
app.post('/api/webhooks/creem', async (c) => {
  return handleCreemWebhook(c);
});

// Contety callback (public endpoint — Contety sends POST when async content is ready)
//
// If `global_settings.contety_callback_secret` is configured we require
// callers to present it via `X-Contety-Secret`. The secret is optional for
// backwards compatibility but should be set in production to keep
// strangers from probing tracking record state by guessing content_ids.
app.post('/api/contety/callback', async (c) => {
  try {
    const secretRow = await c.env.DB.prepare(
      "SELECT value FROM global_settings WHERE key = 'contety_callback_secret'"
    ).first<{ value: string }>();
    if (secretRow?.value) {
      const provided = c.req.header('x-contety-secret') || '';
      if (provided !== secretRow.value) {
        return c.json({ error: 'Unauthorized' }, 401);
      }
    }

    const body = await c.req.json<{ process_type?: string; content_id?: number; status?: string }>();
    if (!body.content_id || !body.status) {
      return c.json({ error: 'Missing content_id or status' }, 400);
    }

    // Find the tracking record
    const record = await c.env.DB.prepare(
      'SELECT cc.*, cfg.auto_import, cfg.default_status, cfg.default_category_id, cfg.default_author_id, cfg.api_key as site_api_key FROM contety_contents cc LEFT JOIN contety_configs cfg ON cfg.site_id = cc.site_id WHERE cc.contety_content_id = ? AND cc.status = ?'
    ).bind(body.content_id, 'processing').first<any>();

    if (!record) {
      return c.json({ success: true, message: 'No matching record' });
    }

    if (body.status === 'completed') {
      // Get API key for fetching content detail
      const apiKey = record.site_api_key || await c.env.DB.prepare(
        'SELECT api_key FROM global_contety_config WHERE is_enabled = 1 LIMIT 1'
      ).bind().first<any>().then((r: any) => r?.api_key);

      if (apiKey && record.auto_import === 1) {
        const { getContentDetail, importContentAsPost } = await import('./lib/contety');
        const detail = await getContentDetail(apiKey, body.content_id);

        if (detail.status === 'completed') {
          const postId = await importContentAsPost(c.env.DB, c.env.R2, record.site_id, detail, {
            default_status: record.default_status || 'draft',
            default_category_id: record.default_category_id,
            default_author_id: record.default_author_id,
          });

          await c.env.DB.prepare(
            'UPDATE contety_contents SET status = ?, post_id = ?, title = ?, updated_at = datetime(?) WHERE id = ?'
          ).bind('completed', postId, detail.title, new Date().toISOString(), record.id).run();

          await c.env.DB.prepare(
            'INSERT INTO contety_logs (site_id, action, contety_content_id, post_id, credits_used, status) VALUES (?, ?, ?, ?, ?, ?)'
          ).bind(record.site_id, 'callback_import', body.content_id, postId, detail.credits || 0, 'success').run();
        }
      } else {
        // Just mark as completed, user will manually import
        await c.env.DB.prepare(
          'UPDATE contety_contents SET status = ?, updated_at = datetime(?) WHERE id = ?'
        ).bind('completed', new Date().toISOString(), record.id).run();
      }
    } else if (body.status === 'failed') {
      await c.env.DB.prepare(
        'UPDATE contety_contents SET status = ?, error_message = ?, updated_at = datetime(?) WHERE id = ?'
      ).bind('failed', 'Content generation failed on Contety', new Date().toISOString(), record.id).run();

      await c.env.DB.prepare(
        'INSERT INTO contety_logs (site_id, action, contety_content_id, status, error_message) VALUES (?, ?, ?, ?, ?)'
      ).bind(record.site_id, 'callback_failed', body.content_id, 'failed', 'Content generation failed').run();
    }

    return c.json({ success: true });
  } catch (err: any) {
    console.error('Contety callback error:', err.message);
    return c.json({ error: 'Internal error' }, 500);
  }
});

// ---- Short URL public route ----
app.route('/git', gitRoutes);

// ---- Platform-default legal pages (privacy, terms, KVKK, distance sales,
// refunds, cookies, status, contact) ----
// Mounted under /legal so it never collides with the CMS `/:slug` page
// route. Site admins who want custom copy can publish their own page
// without conflict.
app.route('/legal', legalRoutes);

// TEMP: Site-template visual-proof prototypes (Faz 0). Remove once a
// magazine direction is chosen and the real template is built.
app.route('/__proto', protoRoutes);

// ---- Language switcher ----
// GET /set-lang/:lang?next=<path> sets the cms_lang cookie and bounces
// back. The i18n middleware reads that cookie above Accept-Language, so a
// manual flag click persists across the whole site.
app.route('/set-lang', setLangRoutes);

// ---- Landing / Marketing page ----
// Helper: check if host is an admin domain (primary or workers.dev fallback)
function isAdminHost(host: string, env: Bindings): boolean {
  const adminDomain = (env.ADMIN_DOMAIN || '').toLowerCase().replace(/:\d+$/, '');
  if (adminDomain && (host === adminDomain || host === `www.${adminDomain}`)) return true;
  // Also allow workers.dev subdomain as admin
  if (host.endsWith('.workers.dev')) return true;
  return false;
}

// Serve landing at / on admin domain (before other public routes)
app.get('/', async (c, next) => {
  const host = (c.req.header('host') || '').toLowerCase().replace(/:\d+$/, '');
  if (isAdminHost(host, c.env)) {
    const { serveLanding } = await import('./routes/public/landing');
    const res = await serveLanding(c);
    if (res) return res;
    return c.redirect('/admin/');
  }
  await next();
});

// Serve the landing (in the requested language) at /en and /tr on the
// admin domain too, so the management homepage IS the landing in both
// languages — without this, /en fell through to the CMS blog home.
// Must be registered before the public home route below.
app.get('/:lang{en|tr}', async (c, next) => {
  const host = (c.req.header('host') || '').toLowerCase().replace(/:\d+$/, '');
  if (isAdminHost(host, c.env)) {
    const { serveLanding } = await import('./routes/public/landing');
    const res = await serveLanding(c);
    if (res) return res;
  }
  await next();
});
app.route('/', landingPageRoutes);

// ---- Media serving (R2) ----
// Supports both:
//   /uploads/{path}           → siteId from domain resolution (public sites)
//   /uploads/s/{siteId}/{path} → explicit siteId in URL (admin panel)
app.get('/uploads/*', async (c) => {
  let siteId = c.get('siteId');
  let path = new URL(c.req.url).pathname.replace('/uploads/', '');

  // Support explicit site prefix: /uploads/s/{siteId}/...
  const siteMatch = path.match(/^s\/(\d+)\/(.*)/);
  if (siteMatch) {
    siteId = parseInt(siteMatch[1]);
    path = siteMatch[2];
  }

  if (!siteId) return c.notFound();

  const key = `sites/${siteId}/uploads/${path}`;

  const object = await c.env.R2.get(key);
  if (!object) return c.notFound();

  const contentType = object.httpMetadata?.contentType || 'application/octet-stream';

  const headers = new Headers();
  headers.set('Content-Type', contentType);
  headers.set('Cache-Control', 'public, max-age=31536000, immutable');
  headers.set('ETag', object.etag);
  headers.set('X-Content-Type-Options', 'nosniff');

  // SVG/HTML/XML can carry executable script. They still render fine from
  // <img> tags, but when opened directly this CSP keeps any embedded script
  // from running in the site's origin (stored-XSS via upload).
  if (/svg|html|xml/i.test(contentType)) {
    headers.set('Content-Security-Policy', "default-src 'none'; style-src 'unsafe-inline'; sandbox");
  }

  return new Response(object.body, { headers });
});

// ---- Admin Panel (SPA) ----
// Block /admin access on non-admin domains
const adminGuard = async (c: any, next: any) => {
  const host = (c.req.header('host') || '').toLowerCase().replace(/:\d+$/, '');
  if (!isAdminHost(host, c.env)) {
    return c.notFound();
  }
  await next();
};
app.use('/admin', adminGuard);
app.use('/admin/*', adminGuard);

app.get('/admin', (c) => c.redirect('/admin/'));

// Serve admin static assets using Hono's built-in serveStatic
// Strips /admin prefix so /admin/assets/x.js → assets/x.js in KV
app.get(
  '/admin/*',
  serveStatic({
    root: './',
    manifest,
    rewriteRequestPath: (path) => path.replace(/^\/admin/, ''),
  })
);

// SPA fallback: only for navigation requests (no file extension)
// Asset requests (.js, .css, .woff etc.) that weren't found by serveStatic above get 404
app.get('/admin/*', async (c, next) => {
  const path = new URL(c.req.url).pathname;
  if (/\.\w+$/.test(path)) {
    return c.notFound();
  }
  return serveStatic({
    root: './',
    manifest,
    rewriteRequestPath: () => '/index.html',
  })(c, next);
});

// ---- Track page views (public pages only) ----
// Must be registered BEFORE public route handlers so it wraps them via await next()
// Filters bots, static files, non-HTML responses; records country from CF headers
app.use('*', pageViewTracker);

// ---- Public Site (SSR) ----

// Brand favicon — the hex-prism wordmark (identical to the landing/admin
// logo). Served here so the management site can link to it; registered
// before the SSR catch-all routes so `/:slug` doesn't swallow it.
const FAVICON_SVG = '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32"><rect x="1" y="1" width="30" height="30" rx="8" fill="#0F0F11" stroke="#26262C"/><path d="M8 11 L16 7 L24 11 L24 21 L16 25 L8 21 Z" fill="none" stroke="#F5A524" stroke-width="1.5" stroke-linejoin="round"/><path d="M8 11 L16 15 L24 11 M16 15 L16 25" fill="none" stroke="#F5A524" stroke-width="1.25" stroke-linejoin="round" opacity=".6"/><circle cx="16" cy="15" r="1.6" fill="#F5A524"/></svg>';
app.get('/favicon.svg', (c) =>
  c.body(FAVICON_SVG, 200, {
    'content-type': 'image/svg+xml; charset=utf-8',
    'cache-control': 'public, max-age=86400',
  })
);

// RSS feed & Sitemap (before other routes to avoid conflicts)
app.route('/', feedRoutes);
app.route('/', sitemapRoutes);

// AMP trailing-slash normalisation: /amp/ → /amp
app.get('/amp/', (c) => c.redirect('/amp', 301));

// AMP pages (SSR) — home first, then page routes (more specific), then post routes
app.route('/amp', ampHomeRoutes);      // /amp (homepage), /amp/:lang
app.route('/amp', ampPageRoutes);      // /amp/page/:slug, /amp/:lang/page/:slug
app.route('/amp', ampPostRoutes);      // /amp/:slug, /amp/:lang/:slug

// AMP suffix format: /:slug/amp, /:lang/:slug/amp
// AMP query format: handled inside dynamic route via ?amp=1
app.route('/', ampDynamicRoutes);

// AMP custom domain middleware — if the request's domain is set as a site's amp_custom_domain,
// serve all /:slug paths as AMP content
app.use('*', async (c, next) => {
  const siteId = c.get('siteId');
  if (!siteId) { await next(); return; }

  const path = new URL(c.req.url).pathname;
  // Only intercept simple slug paths, not /api, /admin, /uploads, /amp, /feed, /sitemap etc.
  if (path.startsWith('/api/') || path.startsWith('/admin') || path.startsWith('/uploads/') ||
      path.startsWith('/amp') || path.startsWith('/feed') || path.startsWith('/sitemap')) {
    await next();
    return;
  }

  // Check if this domain is an AMP custom domain
  const host = (c.req.header('host') || '').toLowerCase().replace(/:\d+$/, '');
  const ampDomainSetting = await c.env.DB.prepare(
    "SELECT value FROM settings WHERE site_id = ? AND key = 'amp_custom_domain'"
  ).bind(siteId).first<{ value: string }>();

  if (!ampDomainSetting || !ampDomainSetting.value || ampDomainSetting.value.toLowerCase() !== host) {
    await next();
    return;
  }

  // This IS the AMP custom domain — import and call the dynamic AMP renderer
  const { renderAmpForPost } = await import('./routes/public/amp/dynamic');
  const site = c.get('site') as any;
  const defaultLang = site?.default_language || 'tr';

  // Parse slug from path: /:slug or /:lang/:slug
  const parts = path.split('/').filter(Boolean);
  if (parts.length === 1) {
    return renderAmpForPost(c, defaultLang, parts[0]);
  } else if (parts.length === 2 && /^[a-z]{2}$/.test(parts[0])) {
    return renderAmpForPost(c, parts[0], parts[1]);
  }

  await next();
});

// Public pages (SSR)
app.route('/', searchRoutes);    // /search, /:lang/search
app.route('/', archiveRoutes);   // /category/:slug, /:lang/category/:slug, etc.
app.route('/', homeRoutes);      // / (default lang home), /:lang (non-default lang home)
app.route('/', llmsRoutes);      // /llms.txt, /:slug.md — before postRoutes so .md wins
app.route('/', postRoutes);      // /:slug (default lang), /:lang/:slug (non-default — must be last)

// Visitor gate exemptions. The gate (gate.js) only fronts PUBLIC customer-site
// traffic. Admin panel, API/webhooks, media and the management/admin domain must
// never be gated — otherwise desktop admins and server-to-server webhooks (which
// aren't mobile/Turkish) would be blocked. Proxied customer requests carry the
// real domain in `X-Site-Host`; a bare workers.dev/admin host with no such header
// is our own admin/debug surface, so it is exempt too.
function gateExempt(request: Request, env: Bindings): boolean {
  const url = new URL(request.url);
  const p = url.pathname;
  if (
    p === '/admin' || p.startsWith('/admin/') ||
    p === '/api' || p.startsWith('/api/') ||
    p.startsWith('/uploads/') ||
    p.startsWith('/git/')
  ) return true;

  const xsh = (request.headers.get('x-site-host') || '').trim().toLowerCase().replace(/:\d+$/, '');
  const wire = (request.headers.get('host') || '').toLowerCase().replace(/:\d+$/, '');
  const effective = xsh || wire;
  const admin = (env.ADMIN_DOMAIN || '').toLowerCase();
  if (admin && (effective === admin || effective === `www.${admin}`)) return true;
  // Bare workers.dev with no proxied customer domain = admin/debug access.
  if (!xsh && wire.endsWith('.workers.dev')) return true;
  return false;
}

// D1 aşırı-yük devre kesici. D1 boğulunca (queue dolu) render 500 verir; 500
// upstream cache'e alınamadığı için sel sürekli D1'e vurup çökük tutar. Devre
// kesici: D1 hatası görülünce kısa süre (cooldown) public HTML isteklerine D1'e
// DOKUNMADAN, upstream'in cache'leyebileceği kısa-TTL bir "yükleniyor" sayfası
// döneriz → sel micro-cache'te emilir → D1 kuyruğu boşalır → toparlar.
let d1CooldownUntil = 0;
function loadingResponse(): Response {
  const html = '<!doctype html><html lang="tr"><head><meta charset="utf-8">'
    + '<meta name="viewport" content="width=device-width,initial-scale=1">'
    + '<meta http-equiv="refresh" content="4"><meta name="robots" content="noindex">'
    + '<title>Lütfen bekleyin</title><style>body{font-family:system-ui,-apple-system,sans-serif;'
    + 'display:flex;align-items:center;justify-content:center;min-height:100vh;margin:0;background:#f8fafc;color:#475569}'
    + '.c{text-align:center;padding:24px}.s{width:34px;height:34px;border:3px solid #e2e8f0;border-top-color:#64748b;'
    + 'border-radius:50%;animation:sp 1s linear infinite;margin:0 auto 16px}@keyframes sp{to{transform:rotate(360deg)}}</style>'
    + '</head><body><div class="c"><div class="s"></div><p>Sayfa hazırlanıyor, lütfen birkaç saniye bekleyin…</p></div></body></html>';
  // 200 + kısa max-age: upstream micro-cache mutlaka cache'lesin (503'ü cache'lemeyebilir).
  return new Response(html, { status: 200, headers: { 'Content-Type': 'text/html; charset=utf-8', 'Cache-Control': 'public, max-age=3' } });
}

export default {
  // Reverse-proxy host override. An upstream proxy (e.g. our OpenResty edge)
  // can route a customer domain to this worker over its `*.workers.dev`
  // hostname while carrying the real domain in the `X-Site-Host` header. We
  // rewrite the request URL so canonical links, redirects and `c.req.url`
  // reflect the customer domain; `siteResolver` reads `X-Site-Host` directly
  // for site resolution. All fronted domains are ours, so no shared secret.
  fetch: async (request: Request, env: Bindings, ctx: ExecutionContext) => {
    // Sel kalkanı: `proxy.<ADMIN_DOMAIN>` fallback domenine X-Site-Host'SUZ gelen
    // istekler gerçek müşteri trafiği DEĞİL (o daima X-Site-Host taşır). Bot seli
    // bu bare domene vurup site çözemeden D1'i boğuyordu. D1'e dokunmadan ucuz,
    // önbelleklenebilir yanıt ver (ACME/.well-known hariç — SSL doğrulaması için).
    {
      const rawHost = (request.headers.get('host') || '').toLowerCase().replace(/:\d+$/, '');
      const fallback = `proxy.${(env.ADMIN_DOMAIN || 'fixyonet.com').toLowerCase()}`;
      if (rawHost === fallback && !request.headers.get('x-site-host')) {
        const p = new URL(request.url).pathname;
        if (!p.startsWith('/.well-known/')) {
          return new Response('OK', { status: 200, headers: { 'Content-Type': 'text/plain', 'Cache-Control': 'public, max-age=600' } });
        }
      }
    }

    // Visitor gate. Two levels of control:
    //  1) GATE_ENABLED === '1' — deployment master switch (only the gated
    //     worker sets it, so other deploy targets pay zero overhead).
    //  2) per-site `gate_enabled` setting — toggled from admin → Site Settings,
    //     so each customer site turns its own gate on/off. Default off.
    // Runs before the X-Site-Host rewrite; it only reads IP/country/UA/Accept
    // headers, which are host-independent.
    // reCAPTCHA doğrulama ucu — interstitial'ın otomatik POST'unu karşılar.
    // Gate'ten önce ele alınır (kendisi gate'e tabi değil). Token/skor geçerliyse
    // imzalı "insan" çerezi yazıp geldiği yola geri döner.
    if (env.GATE_ENABLED === '1' && env.RECAPTCHA_SECRET) {
      const tsUrl = new URL(request.url);
      if (tsUrl.pathname === '/__ts-verify' && request.method === 'POST') {
        const form = await request.formData();
        const token = String(form.get('g-recaptcha-response') || '');
        const rp = safePath(String(form.get('rp') || '/'));
        const vip = (request.headers.get('x-forwarded-for') || '').split(',')[0].trim()
          || request.headers.get('cf-connecting-ip') || undefined;
        const ok = await verifyRecaptcha(token, env.RECAPTCHA_SECRET, vip);
        if (ok) {
          return new Response(null, {
            status: 302,
            headers: { Location: rp, 'Set-Cookie': await makeHumanCookie(env.RECAPTCHA_SECRET), 'Cache-Control': 'no-store' },
          });
        }
        return new Response(
          '<!doctype html><meta charset="utf-8"><title>Doğrulama Başarısız</title><body style="font-family:sans-serif;text-align:center;padding:48px;color:#444"><div style="font-size:38px">&#9888;&#65039;</div><h2>Doğrulama Başarısız</h2><p style="color:#777">Bağlantınız doğrulanamadı. Lütfen tekrar deneyin.</p></body>',
          { status: 403, headers: { 'Content-Type': 'text/html; charset=utf-8', 'Cache-Control': 'no-store' } }
        );
      }
    }

    // Devre kesici: D1 cooldown'dayken public HTML isteğine D1'e vurmadan
    // cache'lenebilir "yükleniyor" sayfası dön (sel micro-cache'te emilsin).
    const wantsHtmlReq = (request.headers.get('Accept') || '').includes('text/html');
    // MAINTENANCE='1' → TÜM public (muaf olmayan) isteklere D1'e HİÇ dokunmadan
    // loading dön (botlar text/html göndermeyebilir; onları da yakala ki D1
    // sıfır sorguyla toparlasın). Cooldown ise devre kesicinin otomatik hâli.
    if (!gateExempt(request, env) && (env.MAINTENANCE === '1' || Date.now() < d1CooldownUntil)) {
      return loadingResponse();
    }

    let gatedNoStore = false;
    if (env.GATE_ENABLED === '1' && !gateExempt(request, env)) {
      const gateHost = (request.headers.get('x-site-host') || request.headers.get('host') || '')
        .trim().toLowerCase().replace(/:\d+$/, '');
      if (gateHost) {
       try {
        // Gate ayarlarını KV'de kısa süre cache'le — D1'i her istekte yorma
        // (aksi halde sel altında D1 boğulur ve tüm site 500 verir).
        let gsObj: Record<string, string> | null = null;
        const ck = `gatecfg:${gateHost}`;
        if (env.CACHE) {
          const cached = await env.CACHE.get(ck);
          if (cached) { try { gsObj = JSON.parse(cached); } catch { /* yok say */ } }
        }
        if (!gsObj) {
          const rows = await env.DB.prepare(
            "SELECT st.key, st.value FROM site_domains sd JOIN settings st ON st.site_id = sd.site_id AND st.key IN ('gate_enabled','gate_ignore_whitelist','gate_allow_mobile','gate_allow_desktop','gate_require_mobile','gate_require_turkish','gate_require_country','gate_require_no_proxy','gate_recaptcha','gate_block_title_tr','gate_block_text_tr','gate_block_title_en','gate_block_text_en') WHERE sd.domain = ?"
          ).bind(gateHost).all<{ key: string; value: string }>();
          gsObj = {};
          for (const r of (rows.results || [])) gsObj[r.key] = r.value;
          if (env.CACHE) ctx.waitUntil(env.CACHE.put(ck, JSON.stringify(gsObj), { expirationTtl: 30 }));
        }
        const gs = new Map(Object.entries(gsObj));
        if (gs.get('gate_enabled') === '1') {
          // Özel engelleme mesajı (admin) — TR başlığı doluysa nedeni belli
          // etmeden tüm engellerde bu gösterilir; boşsa varsayılan mesajlar.
          const btTr = (gs.get('gate_block_title_tr') || '').trim();
          const blockMessage = btTr
            ? {
                tr: [btTr, (gs.get('gate_block_text_tr') || '').trim()] as [string, string],
                en: [(gs.get('gate_block_title_en') || '').trim(), (gs.get('gate_block_text_en') || '').trim()] as [string, string],
              }
            : null;
          // Kurallar site bazlı; ayar yoksa varsayılan AÇIK ('0' ise kapalı).
          // Cihaz izinleri ayrı: mobil varsayılan AÇIK, masaüstü varsayılan KAPALI.
          const blocked = await runGate(request, env, {
            ignoreWhitelist: gs.get('gate_ignore_whitelist') === '1',
            allowMobile: gs.get('gate_allow_mobile') !== '0',
            allowDesktop: gs.get('gate_allow_desktop') === '1',
            requireTurkish: gs.get('gate_require_turkish') !== '0',
            requireCountry: gs.get('gate_require_country') !== '0',
            requireNoProxy: gs.get('gate_require_no_proxy') !== '0',
            blockMessage,
          });
          if (blocked) return blocked;
          // Kurallar geçti. reCAPTCHA açıksa ve geçerli "insan" çerezi yoksa,
          // içerik yerine görünmez doğrulama sayfasını sun (token alan girer).
          if (
            gs.get('gate_recaptcha') === '1' &&
            env.RECAPTCHA_SITE_KEY && env.RECAPTCHA_SECRET &&
            !(await hasValidHumanCookie(request, env.RECAPTCHA_SECRET))
          ) {
            return interstitialHtml(env.RECAPTCHA_SITE_KEY, new URL(request.url).pathname + new URL(request.url).search);
          }
          // Ziyaretçi geçti AMA sayfa gate'e tabi: upstream proxy/CDN bu sayfayı
          // önbelleğe alıp ENGELLENMESİ gereken başka bir ziyaretçiye sunmasın
          // diye yanıtı önbelleklenemez işaretle (proxy her istekte gate'e uğrar).
          gatedNoStore = true;
        }
       } catch (e) {
        // D1/KV hatası (ör. D1 aşırı yük) → kapıyı atla, site ayakta kalsın.
        console.error('[gate] skipped:', (e as Error)?.message);
       }
      }
    }

    const proxied = request.headers.get('x-site-host');
    if (proxied) {
      const clean = proxied.trim().toLowerCase().replace(/:\d+$/, '');
      if (/^[a-z0-9.-]+$/.test(clean)) {
        const url = new URL(request.url);
        url.hostname = clean;
        url.port = '';
        // Rewrite both the URL and the `Host` header so every host-reader in
        // the app (landing/admin routing, www redirects, canonical links)
        // sees the customer domain uniformly, not the workers.dev name.
        const headers = new Headers(request.headers);
        headers.set('host', clean);
        const init: RequestInit = { method: request.method, headers };
        if (request.method !== 'GET' && request.method !== 'HEAD') {
          init.body = request.body;
          (init as { duplex?: 'half' }).duplex = 'half';
        }
        request = new Request(url.toString(), init);
      }
    }
    let response: Response;
    try {
      response = await app.fetch(request, env, ctx);
    } catch (e) {
      // Worker seviyesinde yakalanmamış hata (ör. D1 throw) → devre kesiciyi tetikle.
      d1CooldownUntil = Date.now() + 12000;
      console.error('[fetch] threw, cooldown 12s:', (e as Error)?.message);
      if (wantsHtmlReq) return loadingResponse();
      throw e;
    }
    // CMS 5xx döndüyse (D1 aşırı yük vb.) → devre kesiciyi tetikle, sayfayı emilebilir yap.
    if (response.status >= 500 && !gateExempt(request, env)) {
      d1CooldownUntil = Date.now() + 12000;
      return loadingResponse();
    }
    if (gatedNoStore) {
      const r = new Response(response.body, response);
      r.headers.set('Cache-Control', 'no-store, no-cache, must-revalidate, max-age=0');
      r.headers.delete('ETag');
      r.headers.delete('Last-Modified');
      return r;
    }
    return response;
  },
  async scheduled(event: ScheduledEvent, env: Bindings, ctx: ExecutionContext) {
    const now = new Date().toISOString();
    // Publish scheduled posts
    ctx.waitUntil(
      env.DB.prepare(
        `UPDATE posts SET status = 'publish', updated_at = datetime('now') WHERE status = 'scheduled' AND published_at <= ?`
      ).bind(now).run()
    );
    // Poll processing Contety contents
    ctx.waitUntil(processContetyPolling(env));
    // Check pending domain NS propagation
    ctx.waitUntil(checkPendingDomains(env));
    // Expire ended subscriptions
    ctx.waitUntil(expireSubscriptions(env.DB));
    // Cleanup old plugin execution logs (30 days retention)
    ctx.waitUntil(
      env.DB.prepare("DELETE FROM plugin_execution_logs WHERE created_at < datetime('now', '-30 days')").run()
    );
    // Refresh the system-status snapshot when it is older than its TTL
    // (cron fires every minute; the snapshot only re-fetches every ~5 min).
    ctx.waitUntil(
      getStatusSnapshot(env).then((snap) =>
        isStale(snap) ? refreshStatusSnapshot(env) : null
      )
    );
  },
};
